# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
  
r_binary_packages:
  - gsl 

r_build_args: "--no-manual --no-resave-data"        
r_check_args: "--no-build-vignettes --no-manual --timings"

before_install:
  - sudo apt-get install libgsl0ldbl  
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - Rscript -e 'update.packages(ask = FALSE)'
