# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel

sudo: true
dist: trusty
cache: packages
warnings_are_errors: true

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org  

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

r_binary_packages:
  - stringi 
  - stringr 
  - curl
  - Rcpp 
  - dplyr 
  - ggplot2 
  - KernSmooth    
  - locpol
  - lokern       
  - lpridge
  - pracma
  - Matrix
  - matrixcalc
  - stats
  - mvtnorm
  - DEoptim
  - GA
  - GenSA
  - copulaedas
  - gridExtra
  - methods
  - minpack.lm
  - pso
  - shiny
  - gsl
  - rhandsontable
  - shinyalert
  - grid
  - GGally
  - DT
  - testthat
  - knitcitations
  - knitr

packages:
  - libcurl4-openssl-dev
  - libxml2-dev
  - libgsl0-dev

#r_build_args: "--no-manual --no-resave-data"        
#r_check_args: "--no-build-vignettes --no-manual --timings"

before_install:
#  - sudo apt-get install libgsl0ldbl 
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
#  - Rscript -e 'update.packages(ask = FALSE)'
