# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_build_args: "--no-manual --no-resave-data"

before_install:
  - sudo apt-get install libgsl-dev
  - Rscript -e 'update.packages(ask = FALSE)'
