# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

factorial_cpp <- function(n) {
    .Call('_pumpingtest_factorial_cpp', PACKAGE = 'pumpingtest', n)
}

stehfest_coefficients_cpp <- function(n) {
    .Call('_pumpingtest_stehfest_coefficients_cpp', PACKAGE = 'pumpingtest', n)
}

theis_WF_LT_cpp <- function(p, par1 = 0.0, par2 = 0.0, par3 = 0.0) {
    .Call('_pumpingtest_theis_WF_LT_cpp', PACKAGE = 'pumpingtest', p, par1, par2, par3)
}

papadopulos_cooper_WF_LT_cpp <- function(p, alpha, rho, par = 0.0) {
    .Call('_pumpingtest_papadopulos_cooper_WF_LT_cpp', PACKAGE = 'pumpingtest', p, alpha, rho, par)
}

boulton_WF_LT_cpp <- function(p, par1, par2, par3 = 0.0) {
    .Call('_pumpingtest_boulton_WF_LT_cpp', PACKAGE = 'pumpingtest', p, par1, par2, par3)
}

hantush_jacob_WF_LT_cpp <- function(p, par1, par2 = 0.0, par3 = 0.0) {
    .Call('_pumpingtest_hantush_jacob_WF_LT_cpp', PACKAGE = 'pumpingtest', p, par1, par2, par3)
}

agarwal_recovery_WF_LT_cpp <- function(p, par1 = 0.0, par2 = 0.0, par3 = 0.0) {
    .Call('_pumpingtest_agarwal_recovery_WF_LT_cpp', PACKAGE = 'pumpingtest', p, par1, par2, par3)
}

agarwal_skin_WF_LT_cpp <- function(p, par1, par2, par3) {
    .Call('_pumpingtest_agarwal_skin_WF_LT_cpp', PACKAGE = 'pumpingtest', p, par1, par2, par3)
}

general_radial_flow_WF_LT_cpp <- function(p, par1 = 0.0, par2 = 0.0, par3 = 0.0) {
    .Call('_pumpingtest_general_radial_flow_WF_LT_cpp', PACKAGE = 'pumpingtest', p, par1, par2, par3)
}

cooper_WF_LT_cpp <- function(p, par1 = 0.0, par2 = 0.0, par3 = 0.0) {
    .Call('_pumpingtest_cooper_WF_LT_cpp', PACKAGE = 'pumpingtest', p, par1, par2, par3)
}

neuzil_WF_LT_cpp <- function(p, par1 = 0.0, par2 = 0.0, par3 = 0.0) {
    .Call('_pumpingtest_neuzil_WF_LT_cpp', PACKAGE = 'pumpingtest', p, par1, par2, par3)
}

callViaString <- function(x, arg1, arg2, arg3, funname) {
    .Call('_pumpingtest_callViaString', PACKAGE = 'pumpingtest', x, arg1, arg2, arg3, funname)
}

callViaXPtr <- function(x, arg1, arg2, arg3, xpsexp) {
    .Call('_pumpingtest_callViaXPtr', PACKAGE = 'pumpingtest', x, arg1, arg2, arg3, xpsexp)
}

stehfest_inversion_vector_cpp <- function(t, coeffs, funname, arg1, arg2, arg3) {
    .Call('_pumpingtest_stehfest_inversion_vector_cpp', PACKAGE = 'pumpingtest', t, coeffs, funname, arg1, arg2, arg3)
}

stehfest_inversion_cpp <- function(t, coeffs, funname, arg1, arg2, arg3) {
    .Call('_pumpingtest_stehfest_inversion_cpp', PACKAGE = 'pumpingtest', t, coeffs, funname, arg1, arg2, arg3)
}

theis_well_function_cpp <- function(td, par1 = 0.0, par2 = 0.0, par3 = 0.0) {
    .Call('_pumpingtest_theis_well_function_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

erf_cpp <- function(x) {
    .Call('_pumpingtest_erf_cpp', PACKAGE = 'pumpingtest', x)
}

boulton_well_function_cpp <- function(td, par1, par2, par3 = 0.0) {
    .Call('_pumpingtest_boulton_well_function_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

boulton_well_function_vector_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_boulton_well_function_vector_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

hantush_jacob_well_function_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_hantush_jacob_well_function_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

hantush_jacob_well_function_vector_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_hantush_jacob_well_function_vector_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

general_radial_flow_well_function_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_general_radial_flow_well_function_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

papadopulos_cooper_well_function_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_papadopulos_cooper_well_function_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

papadopulos_cooper_well_function_vector_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_papadopulos_cooper_well_function_vector_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

cooper_well_function_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_cooper_well_function_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

neuzil_well_function_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_neuzil_well_function_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

agarwal_skin_well_function_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_agarwal_skin_well_function_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

warren_root_well_function_cpp <- function(td, par1, par2, par3) {
    .Call('_pumpingtest_warren_root_well_function_cpp', PACKAGE = 'pumpingtest', td, par1, par2, par3)
}

calculate_aquifer_coordinates <- function(nx, ny, xmin, xmax, ymin, ymax) {
    .Call('_pumpingtest_calculate_aquifer_coordinates', PACKAGE = 'pumpingtest', nx, ny, xmin, xmax, ymin, ymax)
}

calculate_distance_well <- function(x0, y0, nx, ny, xmin, xmax, ymin, ymax) {
    .Call('_pumpingtest_calculate_distance_well', PACKAGE = 'pumpingtest', x0, y0, nx, ny, xmin, xmax, ymin, ymax)
}

theis_solution_space <- function(Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax) {
    .Call('_pumpingtest_theis_solution_space', PACKAGE = 'pumpingtest', Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax)
}

boulton_solution_space <- function(Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax) {
    .Call('_pumpingtest_boulton_solution_space', PACKAGE = 'pumpingtest', Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax)
}

papadopulos_solution_space <- function(Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax) {
    .Call('_pumpingtest_papadopulos_solution_space', PACKAGE = 'pumpingtest', Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax)
}

hantush_jacob_solution_space <- function(Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax) {
    .Call('_pumpingtest_hantush_jacob_solution_space', PACKAGE = 'pumpingtest', Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax)
}

general_radial_flow_solution_space <- function(Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax) {
    .Call('_pumpingtest_general_radial_flow_solution_space', PACKAGE = 'pumpingtest', Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax)
}

space_calculation_via_string <- function(model, Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax) {
    .Call('_pumpingtest_space_calculation_via_string', PACKAGE = 'pumpingtest', model, Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax)
}

infinite_aquifer_calculate_drawdown_cpp <- function(model, Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax) {
    .Call('_pumpingtest_infinite_aquifer_calculate_drawdown_cpp', PACKAGE = 'pumpingtest', model, Q, x0, y0, t, hydrpar, nx, ny, xmin, xmax, ymin, ymax)
}

constant_head_theis_well_function_cpp <- function(Q, r1, r2, t, hydrpar) {
    .Call('_pumpingtest_constant_head_theis_well_function_cpp', PACKAGE = 'pumpingtest', Q, r1, r2, t, hydrpar)
}

no_flow_theis_well_function_cpp <- function(Q, r1, r2, t, hydrpar) {
    .Call('_pumpingtest_no_flow_theis_well_function_cpp', PACKAGE = 'pumpingtest', Q, r1, r2, t, hydrpar)
}

constant_head_boulton_well_function_cpp <- function(Q, r1, r2, t, hydrpar) {
    .Call('_pumpingtest_constant_head_boulton_well_function_cpp', PACKAGE = 'pumpingtest', Q, r1, r2, t, hydrpar)
}

no_flow_boulton_well_function_cpp <- function(Q, r1, r2, t, hydrpar) {
    .Call('_pumpingtest_no_flow_boulton_well_function_cpp', PACKAGE = 'pumpingtest', Q, r1, r2, t, hydrpar)
}

